# Generated by Django 5.0.1 on 2026-01-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projetos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=20, unique=True, verbose_name="Número"),
                ),
                ("assunto", models.CharField(max_length=200, verbose_name="Assunto")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("tecnico", "Técnico - Bug"),
                            ("duvida", "Dúvida - Como Fazer"),
                            ("solicitacao", "Solicitação - Nova Feature"),
                            ("financeiro", "Financeiro - Fatura"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=20,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_atendimento", "Em Atendimento"),
                            ("aguardando_cliente", "Aguardando Cliente"),
                            ("resolvido", "Resolvido"),
                            ("fechado", "Fechado"),
                        ],
                        default="aberto",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("anexos", models.JSONField(blank=True, default=list, verbose_name="Anexos")),
                (
                    "data_primeira_resposta",
                    models.DateTimeField(blank=True, null=True, verbose_name="Primeira Resposta"),
                ),
                (
                    "data_resolucao",
                    models.DateTimeField(blank=True, null=True, verbose_name="Data de Resolução"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Aberto em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "atendente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_atendimento",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atendente",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="projetos.projeto",
                        verbose_name="Projeto Relacionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RespostaTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Resposta")),
                ("solucao_proposta", models.TextField(blank=True, verbose_name="Solução Proposta")),
                ("anexos", models.JSONField(blank=True, default=list, verbose_name="Anexos")),
                ("interno", models.BooleanField(default=False, verbose_name="Nota Interna")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Enviado em")),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="suporte.ticket",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta do Ticket",
                "verbose_name_plural": "Respostas do Ticket",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nota",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Nota",
                    ),
                ),
                ("comentario", models.TextField(blank=True, verbose_name="Comentário")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Avaliado em")),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao",
                        to="suporte.ticket",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação do Ticket",
                "verbose_name_plural": "Avaliações de Tickets",
            },
        ),
    ]
