# Generated by Django 4.2.28 on 2026-02-28 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suporte", "0002_alter_ticket_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respostaticket",
            name="conteudo",
            field=models.TextField(
                validators=[
                    django.core.validators.MaxLengthValidator(
                        10000, "Resposta não pode exceder 10.000 caracteres."
                    )
                ],
                verbose_name="Resposta",
            ),
        ),
    ]
