# Generated by Django 5.0.1 on 2026-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site_pt', models.CharField(default='ECOMMDEV', max_length=100, verbose_name='Nome do Site (PT)')),
                ('nome_site_en', models.CharField(default='ECOMMDEV', max_length=100, verbose_name='Nome do Site (EN)')),
                ('tagline_pt', models.CharField(blank=True, max_length=255, verbose_name='Tagline (PT)')),
                ('tagline_en', models.CharField(blank=True, max_length=255, verbose_name='Tagline (EN)')),
                ('descricao_pt', models.TextField(blank=True, verbose_name='Descrição (PT)')),
                ('descricao_en', models.TextField(blank=True, verbose_name='Descrição (EN)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('email_contato', models.EmailField(default='contato@ecommdev.com.br', max_length=254, verbose_name='Email de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('horario_atendimento', models.CharField(blank=True, max_length=100, verbose_name='Horário de Atendimento')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta Keywords')),
                ('meta_description_pt', models.TextField(blank=True, verbose_name='Meta Description (PT)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('lido', 'Lido'), ('respondido', 'Respondido'), ('arquivado', 'Arquivado')], default='novo', max_length=20, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('empresa', models.CharField(blank=True, max_length=100, verbose_name='Empresa')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='depoimentos/', verbose_name='Foto')),
                ('depoimento_pt', models.TextField(verbose_name='Depoimento (PT)')),
                ('depoimento_en', models.TextField(blank=True, verbose_name='Depoimento (EN)')),
                ('avaliacao', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Avaliação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['ordem', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('geral', 'Geral'), ('servicos', 'Serviços'), ('pacotes', 'Pacotes'), ('pagamento', 'Pagamento'), ('suporte', 'Suporte')], default='geral', max_length=20, verbose_name='Categoria')),
                ('pergunta_pt', models.CharField(max_length=300, verbose_name='Pergunta (PT)')),
                ('pergunta_en', models.CharField(blank=True, max_length=300, verbose_name='Pergunta (EN)')),
                ('resposta_pt', models.TextField(verbose_name='Resposta (PT)')),
                ('resposta_en', models.TextField(blank=True, verbose_name='Resposta (EN)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['categoria', 'ordem'],
            },
        ),
    ]
