# Generated by Django 5.2.10 on 2026-01-27 23:20

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaosite",
            name="favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/",
                validators=[core.validators.ImageValidator(max_size=5242880)],
                verbose_name="Favicon",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaosite",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/",
                validators=[core.validators.ImageValidator(max_size=5242880)],
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="depoimento",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="depoimentos/",
                validators=[core.validators.ImageValidator(max_size=5242880)],
                verbose_name="Foto",
            ),
        ),
    ]
