# Generated by Django 5.2.10 on 2026-01-27 23:20

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivoprojeto",
            name="arquivo",
            field=models.FileField(
                upload_to="projetos/arquivos/",
                validators=[core.validators.DocumentValidator(max_size=10485760)],
                verbose_name="Arquivo",
            ),
        ),
    ]
