# Generated by Django 4.2.28 on 2026-02-20 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projetos", "0002_alter_arquivoprojeto_arquivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projetos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cliente",
            ),
        ),
    ]
