"""
Management command to update services with full portfolio data.
Usage: python manage.py update_servicos
"""
from django.core.management.base import BaseCommand
from django.db import transaction
from decimal import Decimal

from servicos.models import Servico


class Command(BaseCommand):
    help = 'Updates services with full portfolio data'

    @transaction.atomic
    def handle(self, *args, **options):
        self.stdout.write('Updating services...')

        # Clear existing services
        Servico.objects.all().delete()

        services_data = [
            # DESENVOLVIMENTO WEB
            {
                'tipo': 'desenvolvimento',
                'nome_pt': 'Sites Institucionais',
                'nome_en': 'Institutional Websites',
                'slug': 'sites-institucionais',
                'descricao_curta_pt': 'Site profissional completo com design responsivo e SEO otimizado',
                'descricao_curta_en': 'Complete professional website with responsive design and optimized SEO',
                'descricao_pt': 'Desenvolvimento de sites institucionais modernos e responsivos, ideais para apresentar sua empresa, serviços e diferenciais de forma profissional na internet.',
                'icone': 'globe',
                'preco': Decimal('2500.00'),
                'tipo_preco': 'apartir',
                'prazo': '15-20 dias úteis',
                'ideal_para': 'Escritórios, consultórios, prestadores de serviços, profissionais liberais',
                'beneficios_pt': [
                    'Design responsivo (mobile, tablet, desktop)',
                    'Até 5 páginas (Home, Sobre, Serviços, Contato, Blog)',
                    'Formulário de contato funcional',
                    'Integração com WhatsApp',
                    'Google Analytics',
                    'SEO básico otimizado',
                    'Hospedagem inclusa (12 meses)',
                    'Certificado SSL (segurança)'
                ],
                'ordem': 1,
                'destaque': True,
            },
            {
                'tipo': 'ecommerce',
                'nome_pt': 'E-commerce Completo',
                'nome_en': 'Complete E-commerce',
                'slug': 'ecommerce-completo',
                'descricao_curta_pt': 'Loja virtual completa com pagamento integrado e gestão de estoque',
                'descricao_curta_en': 'Complete online store with integrated payment and inventory management',
                'descricao_pt': 'Solução completa de e-commerce com todas as funcionalidades necessárias para vender online: catálogo de produtos, carrinho, pagamento, gestão de estoque e muito mais.',
                'icone': 'cart4',
                'preco': Decimal('8000.00'),
                'tipo_preco': 'apartir',
                'prazo': '30-45 dias úteis',
                'ideal_para': 'Lojas físicas expandindo online, revendedores, fabricantes locais',
                'beneficios_pt': [
                    'Catálogo de produtos ilimitado',
                    'Carrinho de compras',
                    'Sistema de pagamento integrado (Mercado Pago/PagSeguro)',
                    'Painel administrativo completo',
                    'Gestão de estoque',
                    'Cálculo de frete automático (Correios)',
                    'Cupons de desconto',
                    'Relatórios de vendas',
                    'Notificações por e-mail/WhatsApp',
                    '3 meses de suporte técnico'
                ],
                'ordem': 2,
                'destaque': True,
            },
            {
                'tipo': 'landing',
                'nome_pt': 'Landing Pages de Alta Conversão',
                'nome_en': 'High Conversion Landing Pages',
                'slug': 'landing-pages',
                'descricao_curta_pt': 'Páginas focadas em conversão para suas campanhas de marketing',
                'descricao_curta_en': 'Conversion-focused pages for your marketing campaigns',
                'descricao_pt': 'Landing pages otimizadas para converter visitantes em leads ou clientes. Design estratégico com foco em resultados para suas campanhas publicitárias.',
                'icone': 'rocket-takeoff',
                'preco': Decimal('1500.00'),
                'tipo_preco': 'apartir',
                'prazo': '7-10 dias úteis',
                'ideal_para': 'Lançamento de produtos, campanhas publicitárias, captação de clientes',
                'beneficios_pt': [
                    'Design focado em conversão',
                    'Formulário de captura de leads',
                    'Integração com ferramentas de e-mail marketing',
                    'Botões de ação estratégicos',
                    'Otimização de velocidade',
                    'Pixel do Facebook/Google Ads',
                    'Hospedagem (12 meses)'
                ],
                'ordem': 3,
                'destaque': False,
            },
            {
                'tipo': 'sistema',
                'nome_pt': 'Sistemas Web Personalizados',
                'nome_en': 'Custom Web Systems',
                'slug': 'sistemas-personalizados',
                'descricao_curta_pt': 'Desenvolvimento sob medida para automatizar seus processos',
                'descricao_curta_en': 'Custom development to automate your processes',
                'descricao_pt': 'Sistemas web personalizados desenvolvidos especificamente para as necessidades da sua empresa. CRMs, ERPs, portais, dashboards e muito mais.',
                'icone': 'gear',
                'preco': Decimal('12000.00'),
                'tipo_preco': 'apartir',
                'prazo': '45-60 dias úteis (conforme complexidade)',
                'ideal_para': 'Empresas com processos específicos que precisam de automação',
                'beneficios_pt': [
                    'Desenvolvimento sob medida',
                    'Painel administrativo',
                    'Múltiplos níveis de usuário',
                    'Relatórios personalizados',
                    'Backup automático',
                    '6 meses de manutenção',
                    'Treinamento da equipe (8 horas)',
                    'Sistema de agendamento online',
                    'Gestão de clientes (CRM)',
                    'Controle de estoque e vendas'
                ],
                'ordem': 4,
                'destaque': True,
            },
            # MANUTENÇÃO E SUPORTE
            {
                'tipo': 'manutencao',
                'nome_pt': 'Plano Essencial',
                'nome_en': 'Essential Plan',
                'slug': 'plano-essencial',
                'descricao_curta_pt': 'Manutenção básica com monitoramento e atualizações de segurança',
                'descricao_curta_en': 'Basic maintenance with monitoring and security updates',
                'descricao_pt': 'Plano de manutenção essencial para manter seu site ou sistema funcionando com segurança e estabilidade.',
                'icone': 'shield-check',
                'preco': Decimal('400.00'),
                'tipo_preco': 'mensal',
                'prazo': 'Contínuo',
                'ideal_para': 'Sites institucionais, blogs, pequenos negócios',
                'beneficios_pt': [
                    'Monitoramento 24/7',
                    'Backup semanal',
                    'Atualizações de segurança',
                    'Correção de bugs críticos',
                    'Suporte por e-mail (resposta em 24h)',
                    '2 horas de ajustes/mês'
                ],
                'ordem': 5,
                'destaque': False,
            },
            {
                'tipo': 'manutencao',
                'nome_pt': 'Plano Profissional',
                'nome_en': 'Professional Plan',
                'slug': 'plano-profissional',
                'descricao_curta_pt': 'Suporte prioritário com horas de desenvolvimento inclusas',
                'descricao_curta_en': 'Priority support with included development hours',
                'descricao_pt': 'Plano completo de manutenção com suporte prioritário, relatórios mensais e horas de desenvolvimento para melhorias contínuas.',
                'icone': 'shield-plus',
                'preco': Decimal('900.00'),
                'tipo_preco': 'mensal',
                'prazo': 'Contínuo',
                'ideal_para': 'E-commerces, sistemas em produção, empresas em crescimento',
                'beneficios_pt': [
                    'Tudo do Plano Essencial',
                    'Backup diário automatizado',
                    'Relatório mensal de desempenho',
                    'Suporte prioritário (resposta em 4h)',
                    '8 horas de desenvolvimento/mês',
                    'Pequenas melhorias e ajustes',
                    'Consultoria técnica'
                ],
                'ordem': 6,
                'destaque': True,
            },
            {
                'tipo': 'manutencao',
                'nome_pt': 'Plano Premium',
                'nome_en': 'Premium Plan',
                'slug': 'plano-premium',
                'descricao_curta_pt': 'Suporte completo com desenvolvimento contínuo e consultoria',
                'descricao_curta_en': 'Complete support with continuous development and consulting',
                'descricao_pt': 'O plano mais completo para empresas que precisam de suporte dedicado, desenvolvimento contínuo e consultoria estratégica.',
                'icone': 'shield-fill-check',
                'preco': Decimal('1800.00'),
                'tipo_preco': 'mensal',
                'prazo': 'Contínuo',
                'ideal_para': 'Empresas com sistemas críticos, operações 24/7',
                'beneficios_pt': [
                    'Tudo do Plano Profissional',
                    'Suporte telefônico/WhatsApp',
                    '20 horas de desenvolvimento/mês',
                    'Novas funcionalidades',
                    'Otimizações de performance',
                    'Gestão de servidor dedicado',
                    'Consultoria estratégica mensal'
                ],
                'ordem': 7,
                'destaque': False,
            },
            # DESIGN E IDENTIDADE VISUAL
            {
                'tipo': 'design',
                'nome_pt': 'Logo + Identidade Visual',
                'nome_en': 'Logo + Visual Identity',
                'slug': 'logo-identidade-visual',
                'descricao_curta_pt': 'Criação de logo profissional e manual de marca',
                'descricao_curta_en': 'Professional logo creation and brand manual',
                'descricao_pt': 'Desenvolvimento de identidade visual completa para sua marca, incluindo logo em diversas versões e manual de aplicação.',
                'icone': 'palette',
                'preco': Decimal('1200.00'),
                'tipo_preco': 'fixo',
                'prazo': '10-15 dias úteis',
                'ideal_para': 'Novas empresas, rebranding, profissionais liberais',
                'beneficios_pt': [
                    '3 propostas de logo',
                    'Versões (colorida, P&B, simplificada)',
                    'Manual de marca básico',
                    'Paleta de cores',
                    'Tipografia definida',
                    'Arquivos em alta resolução'
                ],
                'ordem': 8,
                'destaque': False,
            },
            {
                'tipo': 'design',
                'nome_pt': 'Materiais Gráficos Digitais',
                'nome_en': 'Digital Graphic Materials',
                'slug': 'materiais-graficos',
                'descricao_curta_pt': 'Posts para redes sociais, banners e materiais digitais',
                'descricao_curta_en': 'Social media posts, banners and digital materials',
                'descricao_pt': 'Criação de materiais gráficos digitais para suas redes sociais, site e comunicação corporativa.',
                'icone': 'image',
                'preco': Decimal('300.00'),
                'tipo_preco': 'apartir',
                'prazo': '3-5 dias úteis',
                'ideal_para': 'Empresas ativas nas redes sociais, campanhas promocionais',
                'beneficios_pt': [
                    'Posts para redes sociais (pacote com 10)',
                    'Banners para site',
                    'Assinaturas de e-mail',
                    'Apresentações corporativas',
                    'Cartões digitais'
                ],
                'ordem': 9,
                'destaque': False,
            },
            # MARKETING DIGITAL
            {
                'tipo': 'marketing',
                'nome_pt': 'Consultoria de Marketing Digital',
                'nome_en': 'Digital Marketing Consulting',
                'slug': 'consultoria-marketing',
                'descricao_curta_pt': 'Análise e estratégia para sua presença digital',
                'descricao_curta_en': 'Analysis and strategy for your digital presence',
                'descricao_pt': 'Sessão de consultoria completa para analisar sua presença digital atual e definir estratégias práticas de melhoria.',
                'icone': 'graph-up-arrow',
                'preco': Decimal('800.00'),
                'tipo_preco': 'fixo',
                'prazo': 'Sessão de 2 horas',
                'ideal_para': 'Empresas iniciando no digital, revisão de estratégia',
                'beneficios_pt': [
                    'Análise da presença digital atual',
                    'Estratégia de redes sociais',
                    'Planejamento de conteúdo',
                    'Otimização de anúncios',
                    'Recomendações práticas'
                ],
                'ordem': 10,
                'destaque': False,
            },
            {
                'tipo': 'marketing',
                'nome_pt': 'SEO - Otimização para Google',
                'nome_en': 'SEO - Google Optimization',
                'slug': 'seo-otimizacao',
                'descricao_curta_pt': 'Apareça no Google quando seus clientes buscarem seus serviços',
                'descricao_curta_en': 'Appear on Google when your customers search for your services',
                'descricao_pt': 'Serviço completo de SEO para melhorar o posicionamento do seu site nos resultados de busca do Google.',
                'icone': 'search',
                'preco': Decimal('1500.00'),
                'tipo_preco': 'mensal',
                'prazo': 'Contínuo (resultados em 3-6 meses)',
                'ideal_para': 'Empresas que querem aparecer no Google em todo o Brasil',
                'beneficios_pt': [
                    'Pesquisa de palavras-chave',
                    'Otimização on-page',
                    'Criação de conteúdo otimizado',
                    'Link building local',
                    'Relatórios mensais de posicionamento',
                    'Google Meu Negócio otimizado'
                ],
                'ordem': 11,
                'destaque': False,
            },
            # INTEGRAÇÕES E AUTOMAÇÕES
            {
                'tipo': 'integracao',
                'nome_pt': 'Integrações com Sistemas',
                'nome_en': 'System Integrations',
                'slug': 'integracoes-sistemas',
                'descricao_curta_pt': 'Conecte seu site ou sistema com outras plataformas',
                'descricao_curta_en': 'Connect your website or system with other platforms',
                'descricao_pt': 'Desenvolvimento de integrações personalizadas para conectar seu sistema com APIs de pagamento, ERPs, marketplaces e outras plataformas.',
                'icone': 'plug',
                'preco': Decimal('2500.00'),
                'tipo_preco': 'apartir',
                'prazo': '10-20 dias úteis',
                'ideal_para': 'Empresas com múltiplos sistemas, e-commerces',
                'beneficios_pt': [
                    'APIs de pagamento (Mercado Pago, PagSeguro, Stripe)',
                    'Gateways de SMS/WhatsApp',
                    'Integração com ERPs',
                    'Sincronização com marketplaces',
                    'Conexão com redes sociais',
                    'Ferramentas de e-mail marketing'
                ],
                'ordem': 12,
                'destaque': False,
            },
            {
                'tipo': 'integracao',
                'nome_pt': 'Automações de Processos',
                'nome_en': 'Process Automation',
                'slug': 'automacoes-processos',
                'descricao_curta_pt': 'Automatize tarefas repetitivas e ganhe produtividade',
                'descricao_curta_en': 'Automate repetitive tasks and increase productivity',
                'descricao_pt': 'Desenvolvimento de automações para eliminar tarefas manuais e repetitivas, aumentando a produtividade da sua equipe.',
                'icone': 'robot',
                'preco': Decimal('1800.00'),
                'tipo_preco': 'apartir',
                'prazo': '7-15 dias úteis',
                'ideal_para': 'Empresas com processos manuais repetitivos',
                'beneficios_pt': [
                    'Envio automático de e-mails',
                    'Notificações por WhatsApp',
                    'Geração automática de relatórios',
                    'Sincronização de dados',
                    'Workflows personalizados'
                ],
                'ordem': 13,
                'destaque': False,
            },
            # TREINAMENTO E CONSULTORIA
            {
                'tipo': 'treinamento',
                'nome_pt': 'Treinamento para Equipe',
                'nome_en': 'Team Training',
                'slug': 'treinamento-equipe',
                'descricao_curta_pt': 'Capacite sua equipe para usar o sistema com eficiência',
                'descricao_curta_en': 'Train your team to use the system efficiently',
                'descricao_pt': 'Treinamento completo para sua equipe aprender a utilizar o sistema ou site de forma autônoma e eficiente.',
                'icone': 'mortarboard',
                'preco': Decimal('600.00'),
                'tipo_preco': 'fixo',
                'prazo': '4 horas',
                'ideal_para': 'Equipes que precisam aprender a usar novos sistemas',
                'beneficios_pt': [
                    'Uso do sistema/site',
                    'Boas práticas de gestão',
                    'Atualização de conteúdo',
                    'Material de apoio incluído'
                ],
                'ordem': 14,
                'destaque': False,
            },
            {
                'tipo': 'treinamento',
                'nome_pt': 'Consultoria Técnica',
                'nome_en': 'Technical Consulting',
                'slug': 'consultoria-tecnica',
                'descricao_curta_pt': 'Análise especializada e recomendações para seus projetos',
                'descricao_curta_en': 'Expert analysis and recommendations for your projects',
                'descricao_pt': 'Consultoria técnica especializada para análise de sistemas, auditoria de código, planejamento de projetos e segunda opinião técnica.',
                'icone': 'lightbulb',
                'preco': Decimal('250.00'),
                'tipo_preco': 'hora',
                'prazo': 'Sob demanda',
                'ideal_para': 'Empresas com dúvidas técnicas, avaliação de projetos',
                'beneficios_pt': [
                    'Análise de sistemas existentes',
                    'Recomendações de melhorias',
                    'Auditoria de código',
                    'Planejamento de projetos',
                    'Segunda opinião técnica'
                ],
                'ordem': 15,
                'destaque': False,
            },
            # PACOTES PROMOCIONAIS
            {
                'tipo': 'pacote',
                'nome_pt': 'Pacote Presença Digital Completa',
                'nome_en': 'Complete Digital Presence Package',
                'slug': 'pacote-presenca-digital',
                'descricao_curta_pt': 'Site + Logo + Redes Sociais - Economize R$ 1.500',
                'descricao_curta_en': 'Website + Logo + Social Media - Save R$ 1,500',
                'descricao_pt': 'Pacote completo para quem está começando sua presença digital. Inclui site, identidade visual e gestão inicial de redes sociais.',
                'icone': 'star',
                'preco': Decimal('6500.00'),
                'tipo_preco': 'fixo',
                'prazo': '25-30 dias úteis',
                'ideal_para': 'Novas empresas, profissionais liberais iniciando no digital',
                'beneficios_pt': [
                    'Site institucional (5 páginas)',
                    'Logo + identidade visual',
                    '10 posts para redes sociais',
                    'Cadastro Google Meu Negócio',
                    '3 meses de manutenção',
                    'Economia de R$ 1.500'
                ],
                'ordem': 16,
                'destaque': True,
            },
            {
                'tipo': 'pacote',
                'nome_pt': 'Pacote E-commerce Starter',
                'nome_en': 'E-commerce Starter Package',
                'slug': 'pacote-ecommerce-starter',
                'descricao_curta_pt': 'Loja virtual completa pronta para vender - Economize R$ 2.500',
                'descricao_curta_en': 'Complete online store ready to sell - Save R$ 2,500',
                'descricao_pt': 'Tudo que você precisa para começar a vender online. Loja virtual completa com identidade visual e suporte estendido.',
                'icone': 'star-fill',
                'preco': Decimal('12000.00'),
                'tipo_preco': 'fixo',
                'prazo': '35-45 dias úteis',
                'ideal_para': 'Lojas físicas expandindo para o online',
                'beneficios_pt': [
                    'Loja virtual completa',
                    'Logo + identidade visual',
                    '20 produtos cadastrados',
                    'Integração Mercado Pago',
                    'Treinamento (4 horas)',
                    '6 meses de suporte',
                    'Economia de R$ 2.500'
                ],
                'ordem': 17,
                'destaque': True,
            },
            {
                'tipo': 'pacote',
                'nome_pt': 'Pacote Transformação Digital',
                'nome_en': 'Digital Transformation Package',
                'slug': 'pacote-transformacao-digital',
                'descricao_curta_pt': 'Sistema + Site + Automações - Economize R$ 4.000',
                'descricao_curta_en': 'System + Website + Automation - Save R$ 4,000',
                'descricao_pt': 'Pacote completo para transformação digital da sua empresa. Inclui sistema personalizado, site institucional, automações e suporte premium.',
                'icone': 'trophy',
                'preco': Decimal('18000.00'),
                'tipo_preco': 'fixo',
                'prazo': '60-75 dias úteis',
                'ideal_para': 'Empresas em processo de modernização digital',
                'beneficios_pt': [
                    'Sistema web personalizado',
                    'Site institucional',
                    'Automações de processos',
                    'Treinamento completo',
                    '12 meses de manutenção premium',
                    'Economia de R$ 4.000'
                ],
                'ordem': 18,
                'destaque': True,
            },
        ]

        for data in services_data:
            Servico.objects.create(**data)
            self.stdout.write(f'Created: {data["nome_pt"]}')

        self.stdout.write(self.style.SUCCESS(f'Successfully created {len(services_data)} services!'))
