# Generated by Django 5.0.1 on 2026-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pt', models.CharField(max_length=100, verbose_name='Nome (PT)')),
                ('nome_en', models.CharField(blank=True, max_length=100, verbose_name='Nome (EN)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('descricao_pt', models.TextField(blank=True, verbose_name='Descrição (PT)')),
                ('descricao_en', models.TextField(blank=True, verbose_name='Descrição (EN)')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('cor', models.CharField(default='#0066CC', max_length=20, verbose_name='Cor')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria do Blog',
                'verbose_name_plural': 'Categorias do Blog',
                'ordering': ['ordem', 'nome_pt'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('conteudo', models.TextField(verbose_name='Comentário')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pt', models.CharField(max_length=200, verbose_name='Título (PT)')),
                ('titulo_en', models.CharField(blank=True, max_length=200, verbose_name='Título (EN)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('resumo_pt', models.TextField(blank=True, max_length=500, verbose_name='Resumo (PT)')),
                ('resumo_en', models.TextField(blank=True, max_length=500, verbose_name='Resumo (EN)')),
                ('conteudo_pt', models.TextField(verbose_name='Conteúdo (PT)')),
                ('conteudo_en', models.TextField(blank=True, verbose_name='Conteúdo (EN)')),
                ('imagem_destaque', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagem de Destaque')),
                ('meta_title_pt', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (PT)')),
                ('meta_title_en', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (EN)')),
                ('meta_description_pt', models.CharField(blank=True, max_length=160, verbose_name='Meta Description (PT)')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, verbose_name='Meta Description (EN)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('agendado', 'Agendado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destacar na Home')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('tempo_leitura', models.PositiveIntegerField(default=5, verbose_name='Tempo de Leitura (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-data_publicacao', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
    ]
