# Generated by Django 4.2.28 on 2026-02-20 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("faturas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatura",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faturas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="fatura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagamentos",
                to="faturas.fatura",
                verbose_name="Fatura",
            ),
        ),
    ]
