# Generated by Django 6.0.1 on 2026-01-18 18:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='ideal_para',
            field=models.TextField(blank=True, verbose_name='Ideal Para'),
        ),
        migrations.AddField(
            model_name='servico',
            name='prazo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prazo de Entrega'),
        ),
        migrations.AddField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='servico',
            name='preco_ate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Até'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo_preco',
            field=models.CharField(choices=[('fixo', 'Preço Fixo'), ('apartir', 'A partir de'), ('mensal', 'Mensal'), ('hora', 'Por Hora')], default='apartir', max_length=20, verbose_name='Tipo de Preço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='beneficios_en',
            field=models.JSONField(blank=True, default=list, verbose_name='Benefícios/Incluído (EN)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='beneficios_pt',
            field=models.JSONField(blank=True, default=list, verbose_name='Benefícios/Incluído (PT)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipo',
            field=models.CharField(choices=[('desenvolvimento', 'Desenvolvimento Web'), ('ecommerce', 'E-commerce'), ('landing', 'Landing Page'), ('sistema', 'Sistema Personalizado'), ('manutencao', 'Manutenção e Suporte'), ('design', 'Design e Identidade Visual'), ('marketing', 'Marketing Digital'), ('integracao', 'Integrações e Automações'), ('treinamento', 'Treinamento e Consultoria'), ('pacote', 'Pacote Promocional')], max_length=20, verbose_name='Tipo'),
        ),
    ]
