# Generated by Django 5.2.10 on 2026-01-27 23:20

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicos", "0002_servico_ideal_para_servico_prazo_servico_preco_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="servicos/",
                validators=[core.validators.ImageValidator(max_size=5242880)],
                verbose_name="Imagem",
            ),
        ),
    ]
