# Generated by Django 5.0.1 on 2026-01-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome_pt", models.CharField(max_length=100, verbose_name="Nome (PT)")),
                ("nome_en", models.CharField(blank=True, max_length=100, verbose_name="Nome (EN)")),
                ("slug", models.SlugField(blank=True, unique=True, verbose_name="Slug")),
                ("icone", models.CharField(blank=True, max_length=50, verbose_name="Ícone")),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Categoria de Portfólio",
                "verbose_name_plural": "Categorias de Portfólio",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True, verbose_name="Nome")),
                ("slug", models.SlugField(blank=True, unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titulo_pt", models.CharField(max_length=200, verbose_name="Título (PT)")),
                (
                    "titulo_en",
                    models.CharField(blank=True, max_length=200, verbose_name="Título (EN)"),
                ),
                ("slug", models.SlugField(blank=True, unique=True, verbose_name="Slug")),
                (
                    "cliente",
                    models.CharField(
                        blank=True,
                        help_text="Nome ou setor",
                        max_length=100,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "industria",
                    models.CharField(blank=True, max_length=100, verbose_name="Indústria/Setor"),
                ),
                ("desafio_pt", models.TextField(verbose_name="Desafio (PT)")),
                ("desafio_en", models.TextField(blank=True, verbose_name="Desafio (EN)")),
                ("solucao_pt", models.TextField(verbose_name="Solução (PT)")),
                ("solucao_en", models.TextField(blank=True, verbose_name="Solução (EN)")),
                ("resultados_pt", models.TextField(blank=True, verbose_name="Resultados (PT)")),
                ("resultados_en", models.TextField(blank=True, verbose_name="Resultados (EN)")),
                (
                    "tecnologias",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Tecnologias Utilizadas"
                    ),
                ),
                (
                    "funcionalidades",
                    models.JSONField(blank=True, default=list, verbose_name="Funcionalidades"),
                ),
                (
                    "tempo_desenvolvimento",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tempo de Desenvolvimento"
                    ),
                ),
                (
                    "imagem_destaque",
                    models.ImageField(upload_to="portfolio/", verbose_name="Imagem de Destaque"),
                ),
                (
                    "imagens",
                    models.JSONField(blank=True, default=list, verbose_name="Galeria de Imagens"),
                ),
                ("url_projeto", models.URLField(blank=True, verbose_name="URL do Projeto")),
                (
                    "metricas",
                    models.JSONField(blank=True, default=dict, verbose_name="Métricas de Sucesso"),
                ),
                ("destaque", models.BooleanField(default=False, verbose_name="Destacar na Home")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "visualizacoes",
                    models.PositiveIntegerField(default=0, verbose_name="Visualizações"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases",
                        to="portfolio.categoriaportfolio",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
                "ordering": ["-destaque", "ordem", "-created_at"],
            },
        ),
    ]
