# Generated by Django 5.2.10 on 2026-01-27 23:20

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="imagem_destaque",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio/",
                validators=[core.validators.ImageValidator(max_size=5242880)],
                verbose_name="Imagem de Destaque",
            ),
        ),
        migrations.CreateModel(
            name="CaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="portfolio/galeria/",
                        validators=[core.validators.ImageValidator(max_size=5242880)],
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(blank=True, max_length=100, verbose_name="Título"),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galeria",
                        to="portfolio.case",
                        verbose_name="Case",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem do Case",
                "verbose_name_plural": "Imagens do Case",
                "ordering": ["ordem"],
            },
        ),
    ]
