# Generated by Django 5.0.1 on 2026-01-18 15:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adicional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome_pt", models.CharField(max_length=100, verbose_name="Nome (PT)")),
                ("nome_en", models.CharField(blank=True, max_length=100, verbose_name="Nome (EN)")),
                ("descricao_pt", models.TextField(blank=True, verbose_name="Descrição (PT)")),
                ("descricao_en", models.TextField(blank=True, verbose_name="Descrição (EN)")),
                (
                    "preco",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Preço"),
                ),
                (
                    "tipo_cobranca",
                    models.CharField(
                        choices=[("unico", "Único"), ("mensal", "Mensal"), ("hora", "Por Hora")],
                        default="unico",
                        max_length=20,
                        verbose_name="Tipo de Cobrança",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Adicional",
                "verbose_name_plural": "Adicionais",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Pacote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("completo", "Completo"),
                            ("premium", "Premium"),
                            ("personalizado", "Personalizado"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Tipo",
                    ),
                ),
                ("nome_pt", models.CharField(max_length=100, verbose_name="Nome (PT)")),
                ("nome_en", models.CharField(blank=True, max_length=100, verbose_name="Nome (EN)")),
                (
                    "subtitulo_pt",
                    models.CharField(blank=True, max_length=200, verbose_name="Subtítulo (PT)"),
                ),
                (
                    "subtitulo_en",
                    models.CharField(blank=True, max_length=200, verbose_name="Subtítulo (EN)"),
                ),
                ("descricao_pt", models.TextField(blank=True, verbose_name="Descrição (PT)")),
                ("descricao_en", models.TextField(blank=True, verbose_name="Descrição (EN)")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Preço",
                    ),
                ),
                (
                    "preco_promocional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço Promocional",
                    ),
                ),
                (
                    "tempo_desenvolvimento",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tempo de Desenvolvimento"
                    ),
                ),
                (
                    "suporte_dias",
                    models.PositiveIntegerField(default=30, verbose_name="Dias de Suporte"),
                ),
                (
                    "horas_treinamento",
                    models.PositiveIntegerField(default=0, verbose_name="Horas de Treinamento"),
                ),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Destacar (Mais Popular)"),
                ),
                (
                    "cor_destaque",
                    models.CharField(
                        default="#0066CC", max_length=20, verbose_name="Cor de Destaque"
                    ),
                ),
                ("icone", models.CharField(blank=True, max_length=50, verbose_name="Ícone")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem de Exibição")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Pacote",
                "verbose_name_plural": "Pacotes",
                "ordering": ["ordem", "preco"],
            },
        ),
        migrations.CreateModel(
            name="RecursoPacote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titulo_pt", models.CharField(max_length=200, verbose_name="Recurso (PT)")),
                (
                    "titulo_en",
                    models.CharField(blank=True, max_length=200, verbose_name="Recurso (EN)"),
                ),
                ("incluido", models.BooleanField(default=True, verbose_name="Incluído")),
                ("destaque", models.BooleanField(default=False, verbose_name="Destaque")),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "pacote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recursos",
                        to="pacotes.pacote",
                        verbose_name="Pacote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso do Pacote",
                "verbose_name_plural": "Recursos do Pacote",
                "ordering": ["ordem"],
            },
        ),
    ]
