# Generated by Django 5.2.10 on 2026-01-27 23:20

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_add_email_verification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="usuarios/fotos/",
                validators=[core.validators.AvatarValidator(max_size=2097152)],
                verbose_name="Foto",
            ),
        ),
    ]
