# Generated by Django 5.2.10 on 2026-01-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="cidade",
            field=models.CharField(max_length=100, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="estado",
            field=models.CharField(max_length=2, verbose_name="Estado"),
        ),
    ]
